# Generated by Django 2.1.7 on 2019-02-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etstnum', models.CharField(max_length=40)),
                ('pnrnum', models.CharField(max_length=40)),
                ('ticketStatus', models.CharField(max_length=40)),
                ('ticketdump', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TravellerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('seatNumber', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=40)),
                ('fare', models.IntegerField()),
                ('etstNumber', models.CharField(max_length=40)),
                ('seatStatus', models.CharField(max_length=40)),
            ],
        ),
    ]
